require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.completions")
require("plugins.everforest")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.lsp_config")
